### ISSUE TITLE
README should link to repo for TR home page

### ISSUE THREAD

**Issue by tantek** [w3c/tr-pages#14]
Too many repos on github.com/w3c to "browse" or attempt to "search" them.

The README for this project, for improving specific TR specs/versions needs to link to the repo for gtihub.com/w3c/tr-homepage or whatever it is where we can see the progress of work on improving /TR itself and file issues / feature requests / suggestions etc.

**Comment by tripu** [comment]
Isn't that other repo w3c/tr-pages itself, @tantek?
