### ISSUE TITLE
Search box: make it sticky

### ISSUE THREAD

**Issue by tripu** [w3c/tr-pages#17]
Make the &ldquo;search&rdquo; box stick to the top of the page on https://w3c.github.io/tr-pages/mockup1/ , so that it doesn't get lost after you scroll down (@tanyeah dixit).

**Comment by tanyeah** [comment]
Either make the search box sticky, or shift it to the sidebar and make *that* sticky

**Comment by tripu** [comment]
@bert-github: &ldquo;please, make it sticky only on desktop (on small screen it would take too much space).&rdquo;

**Comment by michael-n-cooper** [comment]
Denis pointed me to this issue and suggested I reopen with my comment.

I see the list of filter options on https://www.w3.org/TR/ now stays visible as I scroll down the page.

This occludes a significant part of my screen, greatly increasing the difficulty of using the page. It covers nearly 1/3 of the screen, in addition to the 1/4 covered by the sidebar on the left. The usable display area is much smaller than it needs to be, meaning it's much harder to look through the list.

I believe if a person has not used search options when first loading the page, they do not need the extra-quick access while scrolling. So the cost is not worth the benefit.

**Comment by tripu** [comment]
@michael-n-cooper:

I just did some tests. These are with Chromium desktop, with no *zoom*.

**Window `767px` wide (or less), no sticky filters:**

![image](https://user-images.githubusercontent.com/1016538/43942047-cad37238-9c76-11e8-9f63-98b7664d4888.png)

**Window `768px` wide (or more), sticky filters:**

![image](https://user-images.githubusercontent.com/1016538/43942058-d6691bfc-9c76-11e8-97ab-31204a5a6ee5.png)

The filters occupy ~`133px` of height, and I think this is the worst case scenario: when the window is &ge; `854px` wide, the &ldquo;Filter&rdquo; button does not wrap, so all the form controls fit in two lines, and the filters take ~25% less height.

In this particular screenshot, the filters take ~16% of the total height (total is ~`807px`).

To have the filters take 33% of the total height, I have to resize the window down to `768px` &times; `399px`:

![image](https://user-images.githubusercontent.com/1016538/43942583-e684e4ce-9c78-11e8-9292-dbf9d2f190e0.png)

In any case, the sidebar takes 20% of the width.

---

In general, I think the sticky filters are useful to navigate/winnow this list of ~1,150 elements.
But there may be cases when they get in the way.

What devices and browsers are you using (and with what particular settings)?
Can you share some screenshots?

**Comment by tripu** [comment]
Missing further comments, I'm closing this again.
