### ISSUE TITLE
Normalise look & feel of mockup no. 1?

### ISSUE THREAD

**Issue by tripu** [w3c/tr-pages#19]
My personal opinions only:

* Font size?
* Rounded corners don't fit well with rest of w3.org; make square
* Colours need to be more discreet, and text on top of them more readable (contrast is sometimes too low as they are now)

**Comment by tripu** [comment]
These are suggestions I made to @tanyeah last week (CC @deniak).

**Comment by tanyeah** [comment]
+1 to square edges and discreet colours. I'll work on that. 

@tripu, re: font size, I'm inclined to reduce the size of the standard and draft titles (from 167% to 150%), but leave the rest as they are. Thoughts?

**Comment by tripu** [comment]
I assigned you to this one, @tanyeah.

OK about the new font sizes; we can refine as we go.

**Comment by tanyeah** [comment]
I'm wondering if there's a more convenient way to assign colours to the tag labels, in the long-term. 
Right now, they seem to be manually defined in the CSS file. 

So, what happens when we create a new tag? 

Does the tag creator get to choose a colour? What happens if the tag colour chosen is ... problematic (re: contrast / aesthetic appeal, etc)? Do we have to repeatedly check in and adjust?  

Is there a colour palette we can define from which new tag colours are automatically assigned?

**Comment by tripu** [comment]
> I'm wondering if there's a more convenient way to assign colours to the tag labels, in the long-term.

I say we keep it dead simple for now: let's estimate an initial number of tags, and define colours for them manually. We will worry about extending the palette when we get to make that list of tags dynamic, community-contributed, etc.

* @koalie pointed to the different colours of `<h2>`s on [`nota-bene.org`](https://nota-bene.org/) (I thought those were set dynamically with JS, but turns out they're static, so not sure it's useful).
* @tanyeah pointed to the palette in [`codepen.io/alistairtweedie/pen/RKzByG`](https://codepen.io/alistairtweedie/pen/RKzByG).
* I suggested we use [Superscript](https://www.npmjs.com/package/supers)'s [`palette()`](https://github.com/tripu/superscript/#palette) feature to assign *n* colours to *n* tags; the palette scales automatically and ensures colours are &ldquo;far apart&rdquo; from each other, so that they are distinguishable. See [a demo](https://codepen.io/tripu/pen/JEMBoN/). (I maintain this little library; there are still a few tweaks I want to do to ensure colours are evenly distributed&nbsp;&mdash;&nbsp;eg having different shades for each hue).

@deniak, do you have an estimate of the number of tags?

> Is there a colour palette we can define from which new tag colours are automatically assigned?

Yes! `superscript.palette()`! :)

> What happens if the tag colour chosen is ... problematic (re: contrast / aesthetic appeal, etc)?

What if we use the colours for little circles, with no text on top? It would be like a colour &ldquo;badge&rdquo; displayed next to each tag/category (but text would be always black on white). That way, we don't have to deal with contrast issues etc.

**Comment by deniak** [comment]
> @deniak, do you have an estimate of the number of tags?

We will probably start with something between 10-20 tags but the list will grow depending on the needs. I think it's important to keep to short, concise and well-defined list to avoid confusion when the readers select a tag.

**Comment by tripu** [comment]
Closed by @tanyeah.
