### ISSUE TITLE
Get rid of jQuery + Filtrify dependencies?

### ISSUE THREAD

**Issue by tripu** [w3c/tr-pages#20]
We tend to prefer vanilla HTML, CSS and JS; for various reasons&nbsp;&mdash;&nbsp;especially when the same features can be easily achieved without dependencies.

It'd be ideal to do the searching and filtering without [Filtrify](https://luis-almeida.github.io/filtrify/), which in turn depends on jQuery.

**Comment by deniak** [comment]
:+1: to vanilla HTML/CSS/JS!
