### ISSUE TITLE
?status=cr returns 0 specs, but starting on an empty page, then filtering by 'status=CR' returns 59 specs

### ISSUE THREAD

**Issue by tripu** [w3c/tr-pages#37]

**Comment by tripu** [comment]
Ditto about ?status=lc

**Comment by tripu** [comment]
@deniak, looking at `tr-new`, I think these discrepancies come from the filtering server-side (JS filters client-side seem to be working well, at least in these two examples I found). Assigning it to you to investigate, please.

**Comment by deniak** [comment]
Fixed and will deploy later today
