### ISSUE TITLE
Add new maturity levels (e.g., "Amended Recommendation") to status dropdown

### ISSUE THREAD

**Issue by koalie** [w3c/tr-pages#42]
Ensure that new REC track status are present in the status dropdown.
cf. [Process 2018 changes](https://www.w3.org/2018/Process-20180201/#changes) and [list of maturity levels](https://www.w3.org/2018/Process-20180201/#maturity-levels)

**Comment by plehegar** [comment]
New Process 2020 in place and status dropdown updated.
We are not planning to add Amended Recommendation. It's a Recommendation, and will likely be removed from P2021.
