### ISSUE TITLE
Hide retired specs by default

### ISSUE THREAD

**Issue by deniak** [w3c/tr-pages#54]
By default, the retired specifications shouldn't appear on /TR but we should give the option (checkbox?) to include them in the result.

**Comment by plehegar** [comment]
@deniak indicated he can do this one within 2 weeks.

**Comment by deniak** [comment]
@tripu I'll add a checkbox to the UI so people can check it if they want to see retired specs. By default, they won't be displayed, ok?

**Comment by deniak** [comment]
Instead of going with the checkbox, we'll simply hide the retired specifications by default unless 'retired' is selected as a status, since it's already an option.
