### ISSUE TITLE
Please offer a linear (non-card) view

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tr-pages#55]
Hi all,

Thank you for the work on the revised TR page!

If the project is continuing I would like to request an additional view, essentially the list view.
This is the view I use most in practice, as it makes it very easy to scan dates and titles, and it's
possible to view a lot of information in a single screen. 

The information order I would prefer is:

    <date> <title> <status> <working group>

where <date> links to the history page and editor names don't need to be shown.

The only view I really care about is sorted by date.  Thank you,

Ian

**Comment by tripu** [comment]
(Description edited slightly to fix a MD error.)

**Comment by tripu** [comment]
@ianbjacobs, thank you.
I'm closing this one as we mentioned the &ldquo;linear&rdquo; view first on #27.
Sorting is also a different open issue.
