### ISSUE TITLE
Retired specs shouldn't sort to the top, even if they're newest

### ISSUE THREAD

**Issue by wseltzer** [w3c/tr-pages#67]
Today's (March 27) /TR is now a sea of XHTML! The default view should either 
- not include Retired specs, or 
- sort them to the bottom

**Comment by deniak** [comment]
duplicate with #54

**Comment by tripu** [comment]
@deniak: is it a duplicate, though? When the user does select the option to see retired specs (#54), shouldn't them still be shown after the really important stuff, somehow? Or dimmed? Just thinking out loud&hellip;

**Comment by deniak** [comment]
If the goal is to have TR represents what the web should look like, then I think it shouldn't list the obsolete/retired specs by default.
However, we should give the option to list them if needed.

**Comment by tripu** [comment]
I agree, we should *not* show those specs by default.

What I meant is: *when* users select the option to see retired specs anyway, shouldn't the retired specs still be shown *after* the others (like @wseltzer suggests), or at least *greyed out*?

**Comment by deniak** [comment]
I'm not a usability expert but if someone clicks on the 'retired' option, I think he's interested in these specs so it doesn't make sense to force him to scroll down.

**Comment by tripu** [comment]
Good point.

I'm not sure either.
I'll have to play with it, and see what the feeling is.
