### ISSUE TITLE
"Reset" button looks like Submit

### ISSUE THREAD

**Issue by wseltzer** [w3c/tr-pages#69]
Move or re-style the Reset button so it doesn't look like a submit button for the filtering (which appears to happen automagically with no submit, but with weird delay).

**Comment by tripu** [comment]
The delay (1.5 s) is there because otherwise the page would change every time you typed or deleted a single character in the &ldquo;title&rdquo; field, or changed one of the drop-down menus. (We could add a &ldquo;submit&rdquo; button instead and not filter automatically, but it'd make the UI slower, and we would need to fit yet another control in the form.)

I'm not sure what a &ldquo;submit&rdquo; button looks like&hellip; that is just a button, with no special styling.

Would &ldquo;✗&rdquo; be more intuitive than &ldquo;reset&rdquo;?

Put in in a different place?

@tanyeah, wdyt?

**Comment by wseltzer** [comment]
@tripu Put it in a different place, yes.

Returning to the page, the automagic is still un-intuitive. Once I've filtered, the page shouldn't change automatically back to the unfiltered view, which it seems to do.

**Comment by tripu** [comment]
For the moment, I've assigned this issue to myself. I'll try to find a better place/appearance for that button.

@wseltzer, I don't understand what you mean, sorry. *&ldquo;Once I've filtered, the page shouldn't change automatically back to the unfiltered view.&rdquo;* The page changes whenever one changes the filters in any way (after that delay of 1.5 s)&nbsp;&mdash;&nbsp;either adding a filter, modifying one, removing one, or *resetting* all of them at once. It does not change &ldquo;automatically back to the unfiltered view&rdquo; unless the user has clicked that &ldquo;reset&rdquo; button (or removed all filters manually one by one).

It should behave like filters here: https://fonts.google.com/ (except there's no delay there).

If it's the delay what's confusing, I'll try reducing it to 0.5 s or so. (My fear, and the reason for that delay in the first place, is that filters modify the layout of the page and the visibility of ~1,100 complex elements on it at once, and that that may take some time on slow platforms and make the interface less responsive&hellip;)

**Comment by wseltzer** [comment]
@tripu I guess it wasn't automatically reverting, but it felt that way, since I wasn't expecting the page to keep changing as I pondered what to type into the form. 

For me, the "fonts" page works because the feedback is instantaneous -- so I know it's changing in response to what I type or delete. Whereas the /TR page delay breaks my instinctive understanding of what's happening. 

I would either remove the delay or remove the automatic action (and make it click-to-submit instead).

**Comment by wseltzer** [comment]
but the reset button still invites pressing because it's in the position where one would expect a Submit

**Comment by tripu** [comment]
I don't know, @wseltzer&hellip; I wonder if others see it the same way as you. It's the only button on the form, and its label is very succinct and unambiguous.
Where would you put it?
(@tanyeah, I appreciate suggestions :)

**Comment by tanyeah** [comment]
@tripu, one thing I can think to do is to increase the button and font size so that the 'Reset' label is more obvious. Position-wise, I think it's fine as it is. 
@wseltzer, would that help?
