### ISSUE TITLE
What is the use of Version field on search?

### ISSUE THREAD

**Issue by ugultopu** [w3c/tr-pages#89]
Doesn't _Status_ already imply _Version_? I'm confused by this because I was trying to find the latest CSS standard, which I believe is [CSS 2.1]. To do so, I put:

- "CSS" to _Tag_
- "Recommendation" to _Status_
- "Latest" to _Version_

but CSS 2.1 did not show up. It showed up when I removed the _Version_ criteria. Then, by trial and error, I discovered that CSS 2.1 is listed in _Version_: "Editor's draft".

I didn't expect the latest standard to be under "Editor's draft". Then, thinking about it, _Version_ is already implied by _Status_, isn't it? _Status_ already has values like "Recommendation", "Working Draft", "Retired", etc. which _are_ versions. Is there something that I'm missing here?

[CSS 2.1]: https://www.w3.org/TR/2011/REC-CSS2-20110607/

**Comment by plehegar** [comment]
It seems a bug that https://www.w3.org/TR/?title=css&status=rec&version=latest doesn't return CSS 2.1 indeed.

@deniak , any idea on how we ended up here?

**Comment by deniak** [comment]
There was indeed an issue with that spec because of how the WG decided to manage the next version of CSS.
This should now be fixed.
